/*
Package reqcontext contains the request context. Each request will have its own
instance of RequestContext, created by the middleware code in
api-context-middleware.go (parent package) and stored in the request's
context.Context.

Each value here should be assumed valid only per request only, with some
exceptions like the logger.
*/
package reqcontext

import (
	"context"

	"github.com/sirupsen/logrus"
)

// RequestContext is the context of the request, for request-dependent parameters
type RequestContext struct {
	// ID is the unique identifier of the request, generated by the router middleware.
	ID string

	// Logger is a custom field logger for the request
	Logger logrus.FieldLogger
}

// contextKey is an unexported type used as the key for the RequestContext value,
// so that it cannot collide with keys defined in other packages.
type contextKey struct{}

var key contextKey

// WithContext returns a copy of ctx carrying rc.
func WithContext(ctx context.Context, rc RequestContext) context.Context {
	return context.WithValue(ctx, key, rc)
}

// FromContext returns the RequestContext stored in ctx, or the zero value if
// none is present.
func FromContext(ctx context.Context) RequestContext {
	rc, _ := ctx.Value(key).(RequestContext)
	return rc
}
